name: NASA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Install root dependencies (if any)
      - run: npm install
      
      # Install server dependencies
      - name: Install Server Dependencies
        run: npm install
        working-directory: ./server

      # Install client dependencies
      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      # Build client (if applicable)
      - name: Build Client
        run: npm run build
        working-directory: ./client
